services:
  user-service:
    image: user-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: prod
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres
  
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: "user-service"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    ports:
      - "5433:5432"
    networks:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  postgres:
    driver: bridge

volumes:
  db-data: