package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"errors"
	"fmt"
	dbuser "user-service/db/user"
	"user-service/graph/model"
	"user-service/pkg"
	domainuser "user-service/service/user"

	"github.com/google/uuid"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (string, error) {
	id, err := r.userRepository.AddUser(ctx, dbuser.DbUser{
		Email:   input.Email,
		Name:    input.Name,
		Surname: input.Surname,
	})
	if err != nil {
		return "", fmt.Errorf("userRepository.AddUser: %w", err)
	}

	return id.String(), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, id *string) ([]*pkg.User, error) {
	if id == nil {
		users, err := r.userRepository.GetUsers(ctx)
		if err != nil {
			return nil, fmt.Errorf("userRepository.GetUsers: %w", err)
		}

		result := make([]*pkg.User, 0, len(users))
		for _, user := range users {
			u := domainuser.MapUserToService(user)
			result = append(result, &u)
		}

		return result, nil
	}

	u, err := r.userRepository.GetUserById(ctx, uuid.MustParse(*id))
	if err != nil {
		return nil, fmt.Errorf("userRepository.GetUserById: %w", err)
	}

	user := domainuser.MapUserToService(u)
	return []*pkg.User{&user}, nil
}

// ID is the resolver for the Id field.
func (r *userResolver) ID(ctx context.Context, obj *pkg.User) (string, error) {
	if obj == nil {
		return "", errors.New("user is nil")
	}

	return obj.Id.String(), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
