// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewUser struct {
	Email   string `json:"Email"`
	Name    string `json:"Name"`
	Surname string `json:"Surname"`
}

type Query struct {
}
